### ISSUE TITLE
Can't assign GPU number

### ISSUE THREAD

**Issue by LeonZh0u** [CogComp/mcqa-expectations#1]
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 10.76 GiB total capacity; 4.92 GiB already allocated; 8.44 MiB free; 5.20 GiB reserved in total by PyTorch)

When I exported GPU=4, the train.sh script still outputs the above error. Is the GPU number specified somewhere else? Thanks.

**Comment by krunal-shah** [comment]
The code was tested on 24GB gpu machines so you can try using larger gpus. Alternatively, you can try using the RoBERTa base model instead of the large model which was used to report the experiments in the paper.

Also, the GPU=x number specifies the id of the gpu to be used and not the number of gpus to be used. The code only supports training on a single gpu machine. Hope this helps!
